### ISSUE TITLE
QUESTION: is there a way to access to the nth element of an array?

### ISSUE THREAD

**Issue by dgago** [Pramod-Devireddy/go-exprtk#1]
I'm doing this:

```
exp := exprtk.NewExprtk()
exp.SetExpression("v[1];")
exp.AddVectorVariable("v")
err := exp.CompileExpression()
if err != nil {
        return err.Error()
}
exp.SetVectorVariableValue("v", []float64{4.0, 4.0, 4.0, 4.0})
res := exp.GetEvaluatedValue()
```

and as a result I get the following exception

```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7a7278]

runtime stack:
runtime.throw(0x95471b, 0x2a)
        /usr/local/go/src/runtime/panic.go:1117 +0x72
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:718 +0x2e5

goroutine 1 [syscall]:
runtime.cgocall(0x766440, 0xc000055e48, 0x765cb5)
        /usr/local/go/src/runtime/cgocall.go:154 +0x5b fp=0xc000055e18 sp=0xc000055de0 pc=0x6cea5b
github.com/Pramod-Devireddy/go-exprtk._Cfunc_getEvaluatedValue(0x293c470, 0x0)
        _cgo_gotypes.go:130 +0x45 fp=0xc000055e48 sp=0xc000055e18 pc=0x7658a5
github.com/Pramod-Devireddy/go-exprtk.GoExprtk.GetEvaluatedValue.func1(0x293c470, 0x4010000000000000)
        /home/dgago/go/pkg/mod/github.com/!pramod-!devireddy/go-exprtk@v1.0.0/exprtk.go:75 +0x4d fp=0xc000055e78 sp=0xc000055e48 pc=0x7660ad
github.com/Pramod-Devireddy/go-exprtk.GoExprtk.GetEvaluatedValue(0x293c470, 0x94dbda)
        /home/dgago/go/pkg/mod/github.com/!pramod-!devireddy/go-exprtk@v1.0.0/exprtk.go:75 +0x2b fp=0xc000055e98 sp=0xc000055e78 pc=0x765dab
main.Eval2(0x72c3a5, 0xc000000180)
        /home/dgago/r/me/sa-rl-be/main.go:186 +0x133 fp=0xc000055f18 sp=0xc000055e98 pc=0x7662d3
main.main()
        /home/dgago/r/me/sa-rl-be/main.go:14 +0x26 fp=0xc000055f88 sp=0xc000055f18 pc=0x766106
runtime.main()
        /usr/local/go/src/runtime/proc.go:225 +0x256 fp=0xc000055fe0 sp=0xc000055f88 pc=0x700e36
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc000055fe8 sp=0xc000055fe0 pc=0x730261
exit status 2
```

Environment is Ubuntu Linux 20.04. Go Version 1.16.

Thanks in advance!

**Comment by vodamiro** [comment]
@dgago According to the https://github.com/ArashPartow/exprtk, you should be able to access N-th element by following syntax: `vN[]` where `N` is the index -> eg: `v1[]` for second element. But haven't tested that.
